weaverplatform/weaver-sdk-js

src/socket.coffee
src/weaver.coffee

Adds disconnect function to weaver and its channel to pass along to socket.io. May also fix servers running out of resources.

Adds first implementation of disconnect functionality

---

README.md
src/socket.coffee
src/weaver.coffee
test/test-suite.coffee
test/weaver/weaver.test.coffee

Added authentication call

---

src/socket.coffee
src/weaver.coffee
test/test-suite.coffee
test/weaver/weaver.test.coffee

Listens for exceptions thrown from weaver-server.

Entity not found

---

.gitignore
Gruntfile.coffee
README.md
dist/weaver-sdk.full.js
package.json
test/weaver/weaver.test.coffee

Added new grunt task dev `$ grunt dev` that generates the weaver-sdk.full.js at the dist folder
In the other hand with the grunt task dist `$ grunt dist` that generates the minified file  weaver-sdk.full.min.js at the dist folder.
Updated the devDependencies and the README.md file

adding minified grunt task for dist

---

.gitignore
Gruntfile.coffee
src/Weaver.coffee

Fixing require Weaver.error to build weaver-sdk.full
Adding dist folder to gitignore file
Adding task to GruntFile:
$ grunt dev --> will creates dist/weaver-sdk.full.js (not uglify) for debugging purposes
$ grunt dist --> will creates dist/weaver-sdk.full.min.js (uglify) for productions purposes
$ grunt --> default will watch to changes on src

adding grunt task and fixing weaver.error require

---

src/WeaverUser.coffee
test/WeaverUser.test.coffee

logIn, logOut, signUp, signOff static
The requirement was to change just logOut and signUp, but logOut and signOff was added too, trying to be more consistent

making logIn, logOut, signUp, signOff static

---

src/CoreManager.coffee
src/SocketController.coffee
src/WeaverUser.coffee
test/WeaverUser.test.coffee

SDK add static function to list all possible users (Name and email)

SDK add static funciton to list all possible users (Name and email)

---

test/WeaverProject.test.coffee
test/test-suite.coffee

Actually just a quick fix to the tests for k8s compatibility

Projects activate

---

Gruntfile.coffee
README.md
src/CoreManager.coffee
src/WeaverModel.coffee
src/WeaverProject.coffee
src/WeaverQuery.coffee
test/WeaverModel.test.coffee
test/WeaverQuery.test.coffee

- updates Gruntfile to include WeaverModel
- adds tests
- makes models persist to db properly

WeaverModel creation tests + persistence refactor

---

package.json
src/WeaverQuery.coffee
test/WeaverQuery.test.coffee
test/roadmap.coffee

Proposed solution

---

package.json
src/Operation.coffee
src/WeaverNode.coffee
src/WriteOperation.coffee
test/WeaverNode.test.coffee

Increment feature implemented

---

src/CoreManager.coffee
src/Weaver.coffee
src/WeaverHistory.coffee
test/WeaverHistory.test.coffee

Dnb 40 tracker

---

dist/weaver-sdk.full.js
src/Weaver.coffee

The setScheduler function is needed for the weaver-sdk-angular. This would allow the angular-sdk to set a callback function on the Promise library so we can trigger the digest cycle in Angular.
See code for changes.

Add setScheduler function

---

test/WeaverUser.test.coffee

Added better test for webtokens. These tests go hand in hand with https://github.com/weaverplatform/weaver-server/pull/67.

Json webtoken

---

src/Operation.coffee
src/Weaver.coffee
src/WeaverNode.coffee
src/WeaverQuery.coffee
src/WeaverRelation.coffee
src/WeaverRelationNode.coffee
test/WeaverNode.test.coffee
test/WeaverQuery.test.coffee
test/WeaverRelation.test.coffee

still one error in the tests, and maybe tests are not complete enough
so only as an impression
use databaes connector: sysunite/weaver-database-virtuoso:0.1.3

Relation with

---

dist/weaver-sdk.full.js
package.json
src/WeaverFile.coffee
test/WeaverFile.test.coffee
yarn.lock

Removed two unnecessary dependencies.
Also we don't expect the dev to have gulp and coffeescript globally installed now.
Updating dependencies to latest stable version can be done with:
```
$ npm run update-deps
```
or
```
$ yarn update-deps
```

Remove unnecessary dependencies

---

src/WeaverQuery.coffee
src/WriteOperation.coffee
test-server/docker-compose.yml
test/WeaverQuery.test.coffee

New flag in weaver query and a test

---

src/WeaverQuery.coffee
test-server/docker-compose.yml
test/WeaverQuery.test.coffee

Improve weaver query

---

test-server/docker-compose.yml
test/WeaverRelation.test.coffee

Extra test for newer weaver-database-virtuoso

---

bower.json
config/custom-environment-variables.coffee
config/default.coffee
dist/weaver-sdk.full.js
gulpfile.coffee
package.json
src/CoreManager.coffee
src/SocketController.coffee
test/WeaverFile.test.coffee

just a PR to have this version npm published

Https self signed cert

---

test/WeaverUser.test.coffee

testing if there is an attempt to sigIn using NoSQL injection

adding test for NoSQL injection attempts

---

.travis.yml
dist/weaver-sdk.full.js
src/WeaverACL.coffee
src/WeaverProject.coffee
test-server/docker-compose.yml
test/Authorization.test.coffee
test/WeaverACL.test.coffee
test/WeaverProject.test.coffee
test/test-suite.coffee

Function acls

---

test/WeaverNode.test.coffee

@malamili That's what you get for asking a question.

Adds node load relation test

---

bower.json
dist/weaver-sdk.full.js
package.json
src/WeaverNode.coffee

Non static load returns correct WeaverNode instance after loading

Fixed non static WeaverNode Load

---

bower.json
dist/weaver-sdk.full.js
package.json
src/WeaverRelation.coffee
test/WeaverRelation.test.coffee

Get the first node from a relation as follows
```js
const firstNode = node.relation('someRelation').first()
```

First node relation

---

test/WeaverQuery.test.coffee

Adds a test for the sorting functionality

Adds sorting test

---

dist/weaver-sdk.full.js
src/CoreManager.coffee
src/WeaverProject.coffee
test/WeaverProject.test.coffee

Cloning project functionality on a WeaverProject. Including a test.

Weav126cloneproject

---

package.json
src/WeaverNode.coffee
src/WeaverQuery.coffee
src/WeaverRelation.coffee
test-server/docker-compose.yml
test/WeaverHistory.test.coffee
test/WeaverNode.test.coffee
test/WeaverProject.test.coffee
test/WeaverQuery.test.coffee
test/WeaverRESAPI.test.coffee
test/WeaverRelation.test.coffee

Makes noRelations and noAttributes default for query so the default uses the new template

No attr rel defaults

---

bower.json
dist/weaver-sdk.full.js
package.json
src/WeaverRelation.coffee

Works by using WeaverQuery X-times faster (where X is the number of nodes in the relation)

New way of loading relations

---

bower.json
dist/weaver-sdk.full.js
package.json
src/WeaverNode.coffee
test/WeaverNode.test.coffee

firstOrCreate will return the first node if found. If not, it will create and save the node.

Add firstOrCreate for WeaverNode

---

package.json
src/CoreManager.coffee
src/WeaverUser.coffee
test-server/docker-compose.yml
test/WeaverUser.test.coffee

Adds a call to the server to retrieve users which also have access to the current project

List users for users

---

src/CoreManager.coffee
src/WeaverProject.coffee
test/WeaverProject.test.coffee

http://jira.sysunite.com/browse/WEAV-138

Weav 138 readonly

---

src/CoreManager.coffee
src/WeaverProject.coffee
test-server/docker-compose.yml
test/WeaverProject.test.coffee
test/test-suite.coffee

http://jira.sysunite.com/browse/WEAV-163

WEAV 163 Renaming projects

---

test-server/docker-compose.yml
test/WeaverQuery.test.coffee

Allowes for multiple select out paths

Multi select out

---

.travis.yml
package.json
src/CoreManager.coffee
src/WeaverNode.coffee
src/WeaverQuery.coffee
test-server/docker-compose.yml
test/WeaverNode.test.coffee
test/WeaverQuery.test.coffee

Introduces node cloning (WEAV-160) and recursive relation out querying (WEAV-170)

Weav 160 duplicate node

---

src/WeaverNode.coffee
test-server/docker-compose.yml
test/Application.test.coffee
test/Authorization.test.coffee
test/Integration.test.coffee
test/WeaverACL.test.coffee
test/WeaverFile.test.coffee
test/WeaverHistory.test.coffee
test/WeaverNode.test.coffee
test/WeaverPlugin.test.coffee
test/WeaverProject.test.coffee
test/WeaverQuery.test.coffee
test/WeaverRESAPI.test.coffee
test/WeaverRelation.test.coffee
test/WeaverUser.test.coffee
test/globalize.coffee
test/test-suite.coffee

Clone functionality was fixed in 0.0.21-SNAPSHOT of the postgresql connector.

Weav 191 fix clone

---

test-server/docker-compose.yml
test/WeaverQueryWildcardRelations.test.coffee

Adds support for "*" relations to nodes.

Weav 189 wildcard relation

---

src/WeaverQuery.coffee
test/WeaverQuerySingleNetwork.test.coffee

150 count mutilation

---

test/WeaverQuery.test.coffee

Tests have been speed up from 24 sec average to 16 sec average

Weav 193 weaverquery test speedup

---

src/WeaverNode.coffee
test-server/docker-compose.yml
test/WeaverNode.test.coffee
test/WeaverQuerySingleNetwork.test.coffee

Allows for contains queries on 'id'

Weav 173 query id 2

---

test/WeaverQuerySingleNetwork.test.coffee

Adds additional test

---

src/CoreManager.coffee
src/WeaverNode.coffee
test/WeaverNode.test.coffee

Fixes saveBatch so the write operations from all nodes passed are collected and send as a batch instead of batches of individual saves.

Makes batchSave more batchy

---

src/Weaver.coffee
test/WeaverNode.test.coffee

Im proposing to always have this option to true

Set _ignoresOutOfDate default to true

---

src/WeaverNode.coffee
test/WeaverNode.test.coffee

Fixes the issue reported in #169

169 fix destroy

---

package.json
test-server/docker-compose.yml
test/WeaverQuery.test.coffee

Updates the connector versions

---

dist/weaver-sdk.full.js
package.json
src/WeaverNode.coffee
test-server/docker-compose.yml
test/WeaverNode.test.coffee

- Handling nicely errors on update out of date
- Feature to override default behaviour when `weaver.setOptions({ignoresOutOfDate: true})`

Override ignore update

---

dist/weaver-sdk.full.js
src/WeaverNode.coffee
test/WeaverNode.test.coffee

Working feature
This feature is based on Carlos his fork and therefor I will work with Carlos to merge this as soon as 206 and 207 PR's are accepted along with this one.

Weav 210 implement sdk increment feature

---

package.json
src/WeaverPlugin.coffee
test-server/docker-compose.yml

Adds optional argument parameters to plugin calls. Previously only required parameters were supported.

Plugin optional

---

dist/weaver-sdk.full.js
package.json
test-server/docker-compose.yml

integration test for: https://github.com/weaverplatform/weaver-database-postgresql/pull/59

Updates connector version to test version

---

package.json
src/WeaverQuery.coffee
test-server/docker-compose.yml
test/WeaverQuerySingleNetwork.test.coffee

Adds the ability to query using recursive relation checks.

Weav 222 recursive

---

dist/weaver-sdk.full.js
package.json
test-server/docker-compose.yml

To test sysunite/weaver-database-postgresql:0.0.29-SNAPSHOT-bigger-upload-size

Test newer connector

---

package.json
test-server/docker-compose.yml

Updates image versions for the graph enabled connector. This PR contains no actual integration tests (those are pending sdk implementation), but shows that the connector does not break existing functionality.

Weav 225 graphs

---

package.json
test-server/docker-compose.yml
test/WeaverQuery.test.coffee

Integration testing of https://github.com/weaverplatform/weaver-database-postgresql/pull/70

Query optimization

---

src/WeaverModel.coffee
test-server/docker-compose.yml
test/WeaverModel.test.coffee
test/WeaverModelQuery.test.coffee

Add initial instances to model.yml loading

Add instance bootstrap

---

src/WeaverModelQuery.coffee
test/WeaverModelQuery.test.coffee

Fixes selectout which were previously flattened

Fixes selectOut on weaver model queries

---

src/WeaverModelClass.coffee
test/WeaverModelQuery.test.coffee

Fixes model database keys being loaded

---

package.json
src/Weaver.coffee
src/WeaverFile.coffee
test/WeaverFile.test.coffee

It's now possible to track down- and upload progress.
Also, filesize and file extension are now available.
Tests are so quick now, you literally can't even.

Add extra functionality to weaver file

---

package.json
src/WeaverModel.coffee
src/WeaverModelClass.coffee
test-server/docker-compose.yml
test/WeaverModel.test.coffee

Add a relation between classes and their super class in WeaverModel bootstrap.

Inherit link in model bootstrap

---

bower.json
package.json
test-server/docker-compose.yml
test/WeaverQuery.test.coffee

Adds tests for the multiple conditions on the same relation key

Weav 258 two restrictions one relation

---

dist/weaver-sdk.full.js
package.json
src/WeaverQuery.coffee
test-server/docker-compose.yml
test/WeaverQuery.test.coffee

Call the 
new Weaver.Query()
.countPerGraph()
support on the connector

Count per graph

---

package.json
src/WeaverQuery.coffee
test-server/docker-compose.yml
test/WeaverGraph.test.coffee
test/WeaverModel.test.coffee
test/WeaverNode.test.coffee

Fixes loading nodes in graphs or the default graph. Previously load would not use any ingraph functionality.

Weav 261 node in graph load

---

test/WeaverRelation.test.coffee

Adds tests for relations on relations

Adds tests for relations on relations

---

bower.json
dist/weaver-sdk.full.js
package.json
src/WeaverModel.coffee
test/WeaverModelQuery.test.coffee

Adds checking of loading instances and .load convenience function.

Adds load function to model classes

---

.travis.yml
karma.conf.js
package.json
src/SocketController.coffee
src/Weaver.coffee
src/WeaverFile.coffee
test/Application.test.coffee
test/WeaverFile.test.coffee
test/WeaverProject.test.coffee
test/WeaverRESTAPI.test.coffee
test/globalize.coffee
yarn.lock

Running tests in a headless chrome environment.
Weaver file is partially supported in the browser.
Some important changes for supporting weaver file in electron are also in there.

Added proper browser testing

---

Changelist.md
src/CoreManager.coffee
src/WeaverModel.coffee
src/WeaverModelQuery.coffee
src/WeaverModelRelation.coffee
src/WeaverQuery.coffee
test-server/weaver-server-models/test-model.yml
test/WeaverACL.test.coffee
test/WeaverModel.test.coffee
test/WeaverModelQuery.test.coffee

Init members are now available on the model in addition to only the classes. This allows for easier querying.

Ws 186 model relation out

---

.github/PULL_REQUEST_TEMPLATE.md

Not applicable, this does not change actualy project functionality

Adds more busywork for developers

---

package.json
test-server/docker-compose.yml
test/WeaverQuery.test.coffee

Fixes a bug in the [no]Relation(In|Out) queries where the restriction on each clause would apply to each clause instead of to their individual ones.

Adds test and new dependency fixing the test

---

dist/weaver-sdk.full.js
package.json
test-server/docker-compose.yml
test-server/weaver-server-config/default.coffee

Any change on sdk.
forget
target branch

testing for travis weaver-server-3.7.0

---

Changelist.md
src/WeaverModelQuery.coffee
test/WeaverModelQuery.test.coffee

Skip multi range check if

---

package.json
src/CoreManager.coffee
test-server/docker-compose.yml
test/WeaverQuery.test.coffee

Weav 264 leave query result alone

---

src/CoreManager.coffee
src/WeaverProject.coffee
test/WeaverProject.test.coffee

Create this call:
```
cm.snapshotProjectGraph('graphName')
```
forget
target branch

Call snapshotGraph

---

package.json
test-server/docker-compose.yml
test/Database.test.coffee
test/WeaverModel.test.coffee
test/WeaverNode.test.coffee

Testbranch for https://github.com/weaverplatform/weaver-database-postgresql/pull/88 (does not add functionality to the SDK)
forget
target branch

Weav 296 support reuse of ids

---

package.json
src/CoreManager.coffee
src/WeaverProject.coffee
test-server/docker-compose.yml
test/WeaverProject.test.coffee

Test new connector
forget
target branch

Snapshot to graphs filter

---

test-server/docker-compose.yml

Update to the latest connector in docker-compose of weaver-sdk
No changes.
forget
target branch

Updates the connector version

---

package.json
test-server/docker-compose.yml
test/WeaverGraphQuery.test.coffee
test/WeaverModelQuery.test.coffee
test/WeaverQuerySingleNetwork.test.coffee

Test PR for https://github.com/weaverplatform/weaver-database-postgresql/pull/91
forget
target branch

Weav 288 count 2

---

package.json
test-server/docker-compose.yml
test/WeaverProject.test.coffee

Test pr for https://github.com/weaverplatform/weaver-database-postgresql/pull/94
forget
target branch

Allow longer database name

---

package.json
test-server/docker-compose.yml

Testing PR for https://github.com/weaverplatform/weaver-database-postgresql/pull/95
forget
target branch

Updates versions for testing

---

package.json
test-server/docker-compose.yml

Merge newly released connector

Upgrades the connector to the release version

---

Changelist.md
package.json
src/WeaverModelClass.coffee

Replaces some model compliance errors with warnings
forget
target branch

makes model compliance less strict

---

Changelist.md
package.json
src/WeaverDefinedNode.coffee
src/WeaverModelClass.coffee
src/WeaverModelQuery.coffee

Less checking on min card

---

.npmignore
package.json

Made branch just for the .npmignore bit
forget
target branch

.npmignore + version bump

---

Changelist.md
src/WeaverModelQuery.coffee
test-server/weaver-server-models/test-doc-model-0.2.0.yml
test/WeaverModelQuery.test.coffee

Fixed inherited keys not being fetched from mapKeys function

---

Changelist.md
src/WeaverModelClass.coffee
test/WeaverModel.test.coffee

The ModelClass .nodeGet and .nodeSet did not work
- [] The automated build passes on the branch this pull request is from
forget
target branch

Nodeset nodeget

---

Changelist.md
src/WeaverQuery.coffee
test/Integration.test.coffee
test/WeaverFile.test.coffee
test/WeaverModel.test.coffee
test/WeaverNode.test.coffee
test/WeaverPlugin.test.coffee
test/WeaverProject.test.coffee
test/WeaverQuery.test.coffee

Throw an error when doing an empty array restrict on WeaverQuery
forget
target branch

Error on empty restrict

---

Changelist.md
src/WeaverModel.coffee
test-server/weaver-server-models/test-model-1.2.0.yml
test/WeaverModel.test.coffee

In some situations with pointing to super clases the model did not load ranges properly.
forget
target branch

Model range bug

---

package.json
test-server/docker-compose.yml

Test PR for https://github.com/weaverplatform/weaver-database-postgresql/pull/100
forget
target branch

Updates connector to cascade performance fix version

---

.gitignore
Changelist.md
dist/weaver-sdk.full.js
package.json
src/CoreManager.coffee
src/WeaverProject.coffee
test-server/docker-compose.yml
test/WeaverProject.test.coffee
yarn.lock

Removing old way to deal with metadata related with apps and providing a more general way to do this.
Related with:
CMDB-96
WE-33
WE-34
forget
target branch

Adding metadata

---

Changelist.md
package.json
src/WeaverModelClass.coffee
test/WeaverModel.test.coffee

Fixes model classes not being able to unset attributes
- x ] I shall promptly fix/reply to comments, as I know PRs are not :fire: and
forget
target branch

Weav 327 fix model unset

---

Changelist.md
dist/weaver-sdk.full.js
package.json
src/WeaverModel.coffee

Add project argument to bootstrap function
forget
target branch

Add project argument to bootstrap function

---

Changelist.md
dist/weaver-sdk.full.js
package.json
src/WeaverModel.coffee

Set project in booststrap query.
forget
target branch

Set project for boostrap query

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

Updates readme

---

package.json
test-server/docker-compose.yml

Test for https://github.com/weaverplatform/weaver-server/pull/170 
forget
target branch

Updates the server version

---

Changelist.md
package.json
src/WeaverQuery.coffee
test-server/docker-compose.yml
test/WeaverQuerySingleNetwork.test.coffee

Docs update in https://github.com/weaverplatform/weaver-docs/pull/1
forget
target branch

Weav 268 select relation

---

dist/weaver-sdk.full.js
package.json
test-server/docker-compose.yml
yarn.lock

Removing chirql as dependency, and setup to be aligned with weaver-server fixed POST body parameters
forget
target branch

Minor changes

---

Changelist.md
dist/weaver-sdk.full.js
package.json
src/WeaverModel.coffee

Readd graph filter in the bootstrap process query that looks for already existing nodes.
forget
target branch

Readd graph filter

---

package.json
test-server/docker-compose.yml

Test weaver-server
forget
target branch

Test the weaver-server sysunite/weaver-server:3.13.3-beta.0

---

Changelist.md
README.md
package.json
src/WeaverNode.coffee
src/WeaverQuery.coffee
src/WeaverRelationIn.coffee
test-server/docker-compose.yml
test/WeaverQuery.test.coffee
test/WeaverQuerySingleNetwork.test.coffee

Weav 200 select in

---

test-server/docker-compose.yml

Use the new weaver-server

---

Changelist.md
src/WeaverNode.coffee
test/WeaverNode.test.coffee

Fixes WEAV-337 and WEAV-338

---

Changelist.md
src/WeaverModelQuery.coffee
test/WeaverModelQuery.test.coffee

fixes WEAV-343

---

Changelist.md
src/WeaverModelRelation.coffee
test/WeaverModelRelation.test.coffee

Implements Weaver.ModelRelation.prototype.load

---

Changelist.md
src/WeaverNode.coffee

Return first of attribute array when it is larger than 1

---

Changelist.md
dist/weaver-sdk.full.js
test-server/docker-compose.yml
test/WeaverQuery.test.coffee
yarn.lock

Weav 360 count with order limit return different results bug

---

Changelist.md
src/WeaverModel.coffee
test-server/weaver-server-models/test-model-1.2.0.yml
test/WeaverModel.test.coffee

Same node in multiple init

---

Changelist.md
src/WeaverModel.coffee
test-server/weaver-server-models/test-model-1.2.0.yml

Rewrite init code for model for 8.6.1 version.
forget
target branch

Better implementation

---

Changelist.md
src/WeaverQuery.coffee
test/WeaverQuery.test.coffee

Add unlimited query
forget
target branch

Test, changelist and implementation

---

Changelist.md
package.json
src/WeaverNode.coffee
test-server/docker-compose.yml
test/WeaverNode.test.coffee

Handle custom data types properly
forget
target branch

Custom datatype

---

src/WeaverModelClass.coffee

only message in error
forget
target branch

One better message

---

package.json
test-server/docker-compose.yml

SDK PR for: https://github.com/weaverplatform/weaver-database-postgresql/pull/108

Updates connector to the feature version

---

Changelist.md
src/WeaverModel.coffee
src/WeaverModelClass.coffee
src/WeaverModelQuery.coffee
src/WeaverModelRelation.coffee
test/WeaverModel.test.coffee
test/WeaverModelQuery.test.coffee

ModelClass get superClass() QOL method + W_M_Q.proto.class() rework CMDB-174

---

test-server/docker-compose.yml

PR for the versions in the associated PRs for connector and weaver.

Updates server and connector

---

dist/weaver-sdk.full.js
src/Weaver.coffee
src/WeaverNodeList.coffee
src/WeaverQuery.coffee
src/WeaverRelation.coffee
test/WeaverNodeList.test.coffee
test/WeaverQuery.test.coffee

Introduces WeaverNodeList

---

package.json
test-server/docker-compose.yml
test/WeaverProject.test.coffee

Some extra tests to check if project id checking works on server side
forget
target branch

Test weaver server 3.15.2

---

test/WeaverModelQuery.test.coffee

Just an extra test
forget
target branch

Model relations in

---

Changelist.md
package.json
src/Weaver.coffee
src/node/Weaver.coffee

Set correct Weaver on the window

---

Changelist.md
src/WeaverModelClass.coffee
src/WeaverNode.coffee
src/wpath.coffee
test/WeaverModel.test.coffee
test/WeaverNode.test.coffee
test/WeaverWpath.test.coffee

Add a function to check if a key is allowed on a ModelClass
forget
target branch

Add allowed relation check

---

Changelist.md
test-server/docker-compose.yml
test/WeaverProject.test.coffee

Test minio bucket name

---

dist/weaver-sdk.full.js

Actually adds dist

---

Changelist.md
src/WeaverModelQuery.coffee
test/WeaverModelQuery.test.coffee

Weav 403 model query select recursive out and always load relations

---

Changelist.md
dist/weaver-sdk.full.js
package.json
src/WeaverModelQuery.coffee
test-server/docker-compose.yml
test/WeaverModelQuery.test.coffee

Release 11.2

---

test-server/docker-compose.yml
test/WeaverFile.test.coffee

Weaver-server clones also minio files now
forget
target branch

Weav 320 clone minio

---

package.json
test/WeaverFile.test.coffee
test/WeaverProject.test.coffee

Fix travis
forget
target branch

Travis error code
