weaverplatform/weaver-sdk-js

src/CoreManager.coffee
src/WeaverFileBrowser.coffee

adding two new endpoints to deal with files using the js SDK from browser environment
The use of the WEAVER fileSystem via js SDK on browser environments will be transparent to the SDK-user but this will implies an increase of the size for the file that is downloaded.

file downloading browser js SDK

---

src/WeaverACL.coffee
src/WeaverRelation.coffee
test/WeaverHistory.test.coffee
test/WeaverRelation.test.coffee
test/WeaverUser.test.coffee
test/globalize.coffee

Removing non-dev dependencies from global namespace in testing. This fixes that these globals are not available in non-test environments.

Removes Promise and cuid from the global namespace

---

package.json
src/SocketController.coffee

This adds the server-version checking functionality. 
Note that the requiredServerVersion in the package.json includes an or clause since prerelease tags never satisify a non-prerelease version. In testing before an official release, this check should be removed (release procedure will be updated to reflect that).

Adds the server-version checking functionality

---

src/WeaverProject.coffee
test/WeaverProject.test.coffee

Fixes Weaver.Project.list() to return functional Projects, which can be destroyed and used in useProject etc.

Issue 82 project list

---

bower.json
dist/weaver-sdk.full.js
package.json
src/WeaverRelation.coffee
test/WeaverRelation.test.coffee

We can now load all nodes in a relation by doing
```js
node.relation('someRelation').load()
.then((nodes) => {
//array of loaded nodes
})
```

Load all nodes in a relation

---

src/WeaverFile.coffee
test/WeaverFile.test.coffee

Adds test illustrating that the server rejects unauthorised access to attachments. Server functionality to reject these is already present in 2.3.2 or prior, this is just a test to prove it.

Adds test to show ACL check on file uploads

---

bower.json
dist/weaver-sdk.full.js
package.json
src/WeaverRelation.coffee
test/WeaverRelation.test.coffee

Important fix for relations. All nodes that were loaded through the load function in WeaverRelation were not updates inside the relation itself. This fixes that issue.

Weaver Relation Fix

---

src/WeaverQuery.coffee
test-server/docker-compose.yml
test/WeaverQuery.test.coffee

New query functionality for nested relation queries and multiple option relation queries.
e.g. 
```
new Weaver.Query().hasNoRelationIn(['a','b'])
new Weaver.Query().hasNoRelationIn('a',['b', 'c'])
new Weaver.Query().hasRelationOut('a',new Weaver.Query().hasRelationOut('b))
```

Weaver query 2.0

---

test-server/docker-compose.yml
test/WeaverQuery.test.coffee

This test now passes because of https://github.com/weaverplatform/weaver-database-postgresql/pull/31

Nested load is fixed in the postgres-connector used

---

package.json
src/WeaverNode.coffee
src/WeaverQuery.coffee
src/WeaverRelation.coffee
test-server/docker-compose.yml
test/WeaverQuery.test.coffee

Select out allows nested nodes to be loaded based on preselected relations.
Note:
```
a -x> b
a -x> c
c -x> b
```
with selectOut(x,x) results in two different WeaverNode instances with id b for now.

Select out

---

src/WeaverNode.coffee
test/Application.test.coffee
test/Authorization.test.coffee
test/Integration.test.coffee
test/WeaverACL.test.coffee
test/WeaverFile.test.coffee
test/WeaverHistory.test.coffee
test/WeaverNode.test.coffee
test/WeaverPlugin.test.coffee
test/WeaverProject.test.coffee
test/WeaverQuery.test.coffee
test/WeaverRESAPI.test.coffee
test/WeaverRelation.test.coffee
test/WeaverUser.test.coffee
test/globalize.coffee
test/test-suite.coffee

Makes wiping of the current project an optional thing that needs to be called explicitly in every test that requires a clean database in order to speed up test speed.
Also fixes Weaver.Node.load(undefined).

Improve test speed

---

package.json
src/SocketController.coffee
test/WeaverProject.test.coffee
test/WeaverQuery.test.coffee

Reverts weaverplatform/weaver-sdk-js#162
This breaks the development build.  Part of the fix is to update the connector version in test-server/docker-compose.yml to 0.0.25-SNAPHOT, but that results in broken tests so needs deeper investigation.

Revert "Weav 203 profile weaverquery end to end"

---

src/Operation.coffee
test/WeaverIdiosyncracy.test.coffee

Raises an error sooner when creating a relation to a destroyed instance of a node. 
Rest is tests showing current behaviour.

Non synchronous idiosyncracies

---

src/CoreManager.coffee

allows node.clone(undefined, 'hasChild')
previously, a target id had to be specified for a clone.

allows node.clone(undefined, 'hasChild')

---

package.json
src/WeaverQuery.coffee
test-server/docker-compose.yml
test/WeaverQuerySingleNetwork.test.coffee

Required for Weaver.Model to load the _proto relation for all nodes.

Add alwaysLoadRelations functionality

---

src/WeaverModel.coffee

This patch allows us to do this in the model:
```yml
ClassOfClass:
init: [
ClassOfAspect,
ClassOfRequirementStatus,
ClassOfStatementStatus,
ClassOfRequirementType,
ClassOfStatementType,
ClassOfRegionInSpace,
ClassOfDocumentRoleType
]
ClassOfAspect:
```
It won't try to double create nodes that are in an init and also in the class definition, and at the same time it will create the correct prototype relations for init.

Patch WeaverModel to support init with defined classes

---

src/WeaverModelRelation.coffee
test-server/weaver-server-models/test-model.yml

PoC for specifying cardinality on a range individually. This is optional (the old way works still), and cardinality is not enforced.

Optionally specify cardinality for a relation range individually

---

Changelist.md
src/WeaverModel.coffee
src/WeaverModelClass.coffee
test/WeaverModel.test.coffee
test/WeaverModelQuery.test.coffee

Instances from any ModelClass extension should not be put in the model graph. By default in the default graph, or set with argument.
forget
target branch

Do not use model graph for instances

---

src/WeaverModelClass.coffee

Prevent the sdk from firing the error:
`X model is not allowed to have the ... relation`
for the inherit and member relation.
forget
target branch

Allow inherit member key

---

Changelist.md
bower.json
package.json
src/WeaverNode.coffee
test/WeaverModel.test.coffee

Fixes a bug where calling load() on an instance of ModelClass would destroy the ModelClass functions
forget
target branch

Fixes .load() issue on ModelClass instances

---

Changelist.md
bower.json
package.json
src/WeaverModelClass.coffee
test/WeaverModel.test.coffee

Fixes ModelClass instances raising an exception when being asked about an attribute they don't have, instead undefined is returned
forget
target branch

Weav 295 get invalid attribute

---

Changelist.md
src/WeaverNode.coffee
test/WeaverNode.test.coffee

Do not use the id of the node as identifier in cycle detection for collecting the pending writes 
forget
target branch

Pending writes get lost 2

---

Changelist.md
package.json
src/WeaverModel.coffee

Only use major model version in graph name for bootstrap
forget
target branch

Use only major version in graph name for model bootstrap

---

Changelist.md
src/WeaverRelation.coffee
test/WeaverRelation.test.coffee

Allows passing of a constructor to Weaver.Relation.prototype.load

---

Changelist.md
src/WeaverModel.coffee

Allow specifying graph in load function on ModelClass
forget
target branch

Use graph argument

---

Changelist.md
src/Error.coffee

Let the Legacy Error object be a JS Error instead just a {} object.
forget
target branch

Return a real error

---

Changelist.md
src/WeaverQuery.coffee
test/WeaverModelQuery.test.coffee

Warn if a user tries to give a sub ModelQuery to a recursive condition.
forget
target branch

Bug weav 362

---

Changelist.md
src/WeaverModel.coffee

Load init instances on Model Context without the need to call bootstrap
forget
target branch

Load init instances on Model Context without the need to call bootstrap

---

Changelist.md
src/WeaverModelClass.coffee
test-server/weaver-server-models/animal-model-1.0.0.yml
test-server/weaver-server-models/test-model-1.1.2.yml
test-server/weaver-server-models/test-model-1.2.0.yml
test/WeaverModel.test.coffee

Read default data type for attributes fro model.
forget
target branch

Use datatype from model

---

Changelist.md
src/WeaverModelRelation.coffee
test/WeaverModel.test.coffee

can't use different references of the same model for `modelRelation.load`

---

test-server/docker-compose.yml
test/WeaverFile.test.coffee

Support uploading multiple files when there is no bucket yet
forget
target branch

Weav 379 upload multipel files when no bucket

---

Changelist.md
package.json
src/WeaverNode.coffee
src/util.coffee
test/WeaverModel.test.coffee
test/WeaverNode.test.coffee
yarn.lock

Switch to moment js for supporting dates and related data types.
forget
target branch

Use moment js

---

Changelist.md
src/WeaverModelQuery.coffee
test/WeaverModelQuery.test.coffee

Throw a descriptive error when no model is supplied as agument for a ModelQuery
forget
target branch

Weav 271 warn when no model
